name: netcheck
version: '1.1.0'
summary: Network connectivity checker with DNS, ping, and port testing
title: NetCheck - Network Connectivity Tester
icon: snap/gui/icon.png
license: GPL-3.0
website: https://github.com/farman20ali/network_access_check
source-code: https://github.com/farman20ali/network_access_check
issues: https://github.com/farman20ali/network_access_check/issues
contact: https://github.com/farman20ali/network_access_check/issues
description: |
  A powerful bash-based network connectivity testing tool that supports:
  
  - ICMP ping testing with statistics and URL support
  - DNS lookup with multiple fallback methods (accepts URLs)
  - Parallel TCP connection testing (up to 256 concurrent jobs)
  - Quick mode parallel processing for wide IP ranges
  - Output file support for quick mode results (-o flag)
  - IP range support (192.168.1.1-50)
  - CIDR notation (10.0.0.0/24)
  - Port ranges (8000-8100) and multiple ports (80,443,3306)
  - CSV file input for bulk testing
  - Multiple output formats (text, JSON, CSV, XML)
  - Comprehensive input validation with helpful warnings
  - Real-time progress tracking
  - Combined reports with dated filenames
  
  Perfect for:
  - System administrators monitoring infrastructure
  - DevOps engineers validating deployments
  - Network diagnostics and troubleshooting
  - DNS resolution verification
  - ICMP connectivity testing
  - Security auditing and port scanning
  - Load balancer health checks
  
  IMPORTANT: For ICMP ping functionality (-p flag), run after installation:
    sudo snap connect netcheck:network-observe
  
  Without this connection, TCP port tests and DNS lookup work normally,
  but ping tests will fail with permission errors.

grade: stable
confinement: strict

base: core22

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  netcheck:
    command: bin/netcheck
    plugs:
      - network
      - network-bind
      - network-observe
      - home
    environment:
      LC_ALL: C.UTF-8
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH

parts:
  netcheck:
    plugin: dump
    source: .
    source-type: local
    organize:
      check_ip.sh: bin/netcheck
    stage:
      - bin/netcheck
      - README.md
      - EXAMPLES.md
      - LICENSE
    stage-packages:
      - telnet
      - netcat-openbsd
      - coreutils
      - grep
      - sed
      - dnsutils
      - iputils-ping
